import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
	],
	format: "cjs",
	target: "es2018",
	jsx: "automatic",
	jsxImportSource: "preact",
	// Render with Preact's React-compatible layer instead of react-dom. The
	// plugin only uses hooks, memo and createRoot, all of which preact/compat
	// supports, and this keeps react-dom's resource-hoisting code (which injects
	// <script>/<link> elements) out of the bundle.
	alias: {
		react: "preact/compat",
		"react-dom": "preact/compat",
		"react-dom/client": "preact/compat/client",
		"react/jsx-runtime": "preact/jsx-runtime",
	},
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	platform: "browser",
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
