import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { createRequire } from "module";

const require = createRequire(import.meta.url);

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Redirect tesseract.js's Node worker to the browser worker so that at runtime
// in Obsidian (Electron renderer) a Web Worker is used with CDN-hosted scripts
// rather than a worker_threads.Worker pointing at a missing local file.
const tesseractBrowserWorkerPlugin = {
	name: "tesseract-browser-worker",
	setup(build) {
		build.onResolve(
			{ filter: /^\.\/worker\/node$/, namespace: "file" },
			(args) => {
				if (!args.importer.includes("tesseract.js")) return null;
				return {
					path: require.resolve(
						"tesseract.js/src/worker/browser/index.js",
					),
				};
			},
		);
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	jsx: "automatic",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	platform: "node",
	plugins: [tesseractBrowserWorkerPlugin],
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
